######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 23 02:05:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainUI/mainui.h hub/hub.h
SOURCES += MainUI/mainui.cpp hub/hub.cpp
RESOURCES += resources.qrc
