######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 23 15:23:01 2011
######################################################################

TEMPLATE = app
TARGET = ./bin/debug/start
DEPENDPATH += . src src/hub src/MainUI
INCLUDEPATH += . src/MainUI src/hub
QT+=webkit xml

# Input
HEADERS += src/hub/hub.h src/MainUI/mainui.h
SOURCES += src/main.cpp src/hub/hub.cpp src/MainUI/mainui.cpp
RESOURCES += src/MainUI/resources.qrc
